services:
    app:
      container_name: hcloud-autosnapshot
      build: .
      image: maralexofficial/hcloud-snapshot-as-backup
      # hostname: hcloud-autosnapshot
      restart: unless-stopped
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        - API_TOKEN=
        - SNAPSHOT_NAME=%name%-%timestamp%-auto
        - LABEL_SELECTOR=AUTOBACKUP
        - KEEP_LAST=3
        - CRON=0 1 * * *
        - NOTIFICATION_TYPE=ntfy

        - NTFY_USER=dein_user
        - NTFY_PASSWORD=dein_passwort
        - NTFY_SERVER=https://example.tld
        - NTFY_TOPIC=hades-notifications
        - NTFY_ENV_FILE=/app/.ntfy.env

        - SMTP_HOST=
        - SMTP_PORT=587
        - SMTP_USER=
        - SMTP_PASS=
        - SMTP_FROM=
        - SMTP_TO=
        - SMTP_TLS=true
