services:
    app:
      container_name: hcloud-snapshot
      build: .
      image: maralexofficial/hcloud-snapshot-as-backup
      restart: unless-stopped
      volumes:
        - ./ntfy-send/.env:/etc/ntfy-send/.env
        - /etc/localtime:/etc/localtime:ro
      environment:
        - API_TOKEN=
        - SNAPSHOT_NAME=%name%-%timestamp%
        - LABEL_SELECTOR=AUTOBACKUP
        - KEEP_LAST=3
        - CRON=0 1 * * *
        - NOTIFICATION_TYPE=ntfy
        #- NTFY_BIN=/usr/bin/ntfy-send
        #- NTFY_TOPIC=hetzner-backup
        - SMTP_HOST=
        - SMTP_PORT=587
        - SMTP_USER=
        - SMTP_PASS=
        - SMTP_FROM=
        - SMTP_TO=
        - SMTP_TLS=true
